function App() {
  let data = [
    {
      word: "wipe",
      pronunciation: "/ waɪp /",
      tooltip: { text: "●●●", title: "Core vocabulary: High-frequency" },
      frequency: [{ text: "S3", title: "Top 3000 spoken words" }],
      partOfSpeech: "verb",
      register: "",
      inflections: "",
      title: "wipe_verb_1",
      images: [],
      geo: "",
      f2n: "",
      meaning: {
        index: "1",
        definition: {
          lexUnit: "",
          registers: [],
          text: "a) to rub a surface with something in order to remove dirt, liquid etc\nb) to clean something by rubbing it against a surface\n",
          synonyms: [],
          oppositions: [],
        },
        translation: "",
        examples: [
          { type: "grammer", text: "wipe something with something" },
          { type: "example", text: "Wipe the table with a damp cloth." },
          {
            type: "example",
            text: "Bill wiped his eyes (= wiped the tears from his face ) and apologized.",
          },
          {
            type: "example",
            text: "He pulled a handkerchief from his pocket and wiped his nose .",
          },
        ],
      },
    },
    {
      word: "wipe",
      pronunciation: "/ waɪp /",
      tooltip: { text: "●●●", title: "Core vocabulary: High-frequency" },
      frequency: [{ text: "S3", title: "Top 3000 spoken words" }],
      partOfSpeech: "verb",
      register: "",
      inflections: "",
      title: "wipe_verb_2",
      images: [],
      geo: "",
      f2n: "",
      meaning: {
        index: "2",
        definition: {
          lexUnit: "",
          registers: [],
          text: "to remove liquid, dirt, or marks by wiping",
          synonyms: [],
          oppositions: [],
        },
        translation: "",
        examples: [
          { type: "grammer", text: "wipe something off/from etc something" },
          { type: "example", text: "Kim wiped the sweat from her face." },
        ],
      },
    },
    {
      word: "wipe",
      pronunciation: "/ waɪp /",
      tooltip: { text: "●●●", title: "Core vocabulary: High-frequency" },
      frequency: [{ text: "S3", title: "Top 3000 spoken words" }],
      partOfSpeech: "verb",
      register: "",
      inflections: "",
      title: "wipe_verb_3",
      images: [],
      geo: "",
      f2n: "",
      meaning: {
        index: "3",
        definition: {
          lexUnit: "",
          registers: [],
          text: "to remove all the information that is stored on a tape, video, or computer disk",
          synonyms: [],
          oppositions: [],
        },
        translation: "",
        examples: [],
      },
    },
    {
      word: "wipe",
      pronunciation: "/ waɪp /",
      tooltip: { text: "●●●", title: "Core vocabulary: High-frequency" },
      frequency: [{ text: "S3", title: "Top 3000 spoken words" }],
      partOfSpeech: "verb",
      register: "",
      inflections: "",
      title: "wipe_verb_9",
      images: [],
      geo: "",
      f2n: "",
      meaning: {
        index: "9",
        definition: {
          lexUnit: "",
          registers: [],
          text: "to dry plates, cups etc that have been washed",
          synonyms: ["dry"],
          oppositions: [],
        },
        translation: "",
        examples: [{ type: "example", text: "You wash, I’ll wipe." }],
      },
    },
    {
      word: "wipe",
      pronunciation: "/ waɪp /",
      tooltip: "",
      frequency: [],
      partOfSpeech: "noun",
      register: "",
      inflections: "",
      title: "wipe_noun_1",
      images: [],
      geo: "",
      f2n: "",
      meaning: {
        index: "1",
        definition: {
          lexUnit: "",
          registers: [],
          text: "a wiping movement with a cloth",
          synonyms: [],
          oppositions: [],
        },
        translation: "",
        examples: [
          {
            type: "example",
            text: "An occasional wipe with a soft cloth will keep the surface shiny.",
          },
          { type: "example", text: "Give the baby’s nose a wipe, would you?" },
        ],
      },
    },
    {
      word: "wipe",
      pronunciation: "/ waɪp /",
      tooltip: "",
      frequency: [],
      partOfSpeech: "noun",
      register: "",
      inflections: "",
      title: "wipe_noun_2",
      images: [],
      geo: "",
      f2n: "",
      meaning: {
        index: "2",
        definition: {
          lexUnit: "",
          registers: [],
          text: "a special piece of wet material that you use to clean someone or something and then throw away",
          synonyms: [],
          oppositions: [],
        },
        translation: "",
        examples: [{ type: "example", text: "a pack of baby wipes" }],
      },
    },
    {
      word: "wipe",
      pronunciation: "/ waɪp /",
      tooltip: { text: "●●●", title: "Core vocabulary: High-frequency" },
      frequency: [{ text: "S3", title: "Top 3000 spoken words" }],
      partOfSpeech: "verb",
      register: "",
      inflections: "",
      title: "wipe_verb_8",
      images: [],
      geo: "",
      f2n: "",
      meaning: {
        index: "8",
        definition: {
          lexUnit:
            "wipe something off the face of the earth/wipe something off the map",
          registers: [],
          text: "to destroy something completely",
          synonyms: [],
          oppositions: [],
        },
        translation: "",
        examples: [
          {
            type: "example",
            text: "Another few years and this species could be wiped off the face of the earth.",
          },
        ],
      },
    },
    {
      word: "wipe",
      pronunciation: "/ waɪp /",
      tooltip: { text: "●●●", title: "Core vocabulary: High-frequency" },
      frequency: [{ text: "S3", title: "Top 3000 spoken words" }],
      partOfSpeech: "verb",
      register: "",
      inflections: "",
      title: "wipe_verb_4",
      images: [],
      geo: "",
      f2n: "",
      meaning: {
        index: "4",
        definition: {
          lexUnit: "wipe something from your mind/memory",
          registers: [],
          text: "to try to forget an unpleasant experience",
          synonyms: [],
          oppositions: [],
        },
        translation: "",
        examples: [],
      },
    },
    {
      word: "wipe",
      pronunciation: "/ waɪp /",
      tooltip: { text: "●●●", title: "Core vocabulary: High-frequency" },
      frequency: [{ text: "S3", title: "Top 3000 spoken words" }],
      partOfSpeech: "verb",
      register: "",
      inflections: "",
      title: "wipe_verb_6",
      images: [],
      geo: "",
      f2n: "",
      meaning: {
        index: "6",
        definition: {
          lexUnit: "wipe the slate clean",
          registers: [],
          text: "to agree to forget about mistakes or arguments that happened in the past",
          synonyms: [],
          oppositions: [],
        },
        translation: "",
        examples: [],
      },
    },
    {
      word: "wipe",
      pronunciation: "/ waɪp /",
      tooltip: { text: "●●●", title: "Core vocabulary: High-frequency" },
      frequency: [{ text: "S3", title: "Top 3000 spoken words" }],
      partOfSpeech: "verb",
      register: "",
      inflections: "",
      title: "wipe_verb_5",
      images: [],
      geo: "",
      f2n: "",
      meaning: {
        index: "5",
        definition: {
          lexUnit: "wipe the floor with somebody",
          registers: ["informal"],
          text: "to defeat someone completely in a competition or argument",
          synonyms: [],
          oppositions: [],
        },
        translation: "",
        examples: [],
      },
    },
    {
      word: "wipe",
      pronunciation: "/ waɪp /",
      tooltip: { text: "●●●", title: "Core vocabulary: High-frequency" },
      frequency: [{ text: "S3", title: "Top 3000 spoken words" }],
      partOfSpeech: "verb",
      register: "",
      inflections: "",
      title: "wipe_verb_7",
      images: [],
      geo: "",
      f2n: "",
      meaning: {
        index: "7",
        definition: {
          lexUnit: "wipe the smile/grin off somebody’s face",
          registers: ["informal"],
          text: "to make someone feel less happy or confident, especially someone who is annoying because they think they are clever",
          synonyms: [],
          oppositions: [],
        },
        translation: "",
        examples: [
          {
            type: "example",
            text: "Tell him how much it’ll cost – that should wipe the smile off his face!",
          },
        ],
      },
    },
  ];
  const nounWords = data.filter((word) => word.partOfSpeech === "noun");
  const verbWords = data.filter((word) => word.partOfSpeech === "verb");
  const phrasalVerbWords = data.filter(
    (word) => word.partOfSpeech === "phrasal verb"
  );
  const adjectiveWords = data.filter(
    (word) => word.partOfSpeech === "adjective"
  );

  const adverbWords = data.filter((word) => word.partOfSpeech === "adverb");
  const suffixWords = data.filter((word) => word.partOfSpeech === "suffix");
  const interjectionWords = data.filter(
    (word) => word.partOfSpeech === "interjection"
  );
  const prepositionWords = data.filter(
    (word) => word.partOfSpeech === "preposition"
  );
  const prefixWords = data.filter((word) => word.partOfSpeech === "prefix");
  /////////////
  const sortedNouns = nounWords.sort(
    (a, b) => Number(a.meaning.index) - Number(b.meaning.index)
  );
  const sortedVerbs = verbWords.sort(
    (a, b) => Number(a.meaning.index) - Number(b.meaning.index)
  );
  const sortedPhrasalVerbs = phrasalVerbWords.sort(
    (a, b) => Number(a.meaning.index) - Number(b.meaning.index)
  );
  const sortedAdjectives = adjectiveWords.sort(
    (a, b) => Number(a.meaning.index) - Number(b.meaning.index)
  );
  const sortedAdverbs = adverbWords.sort(
    (a, b) => Number(a.meaning.index) - Number(b.meaning.index)
  );

  const sortedSuffixes = suffixWords.sort(
    (a, b) => Number(a.meaning.index) - Number(b.meaning.index)
  );
  const sortedInterjections = interjectionWords.sort(
    (a, b) => Number(a.meaning.index) - Number(b.meaning.index)
  );
  const sortedPrepositions = prepositionWords.sort(
    (a, b) => Number(a.meaning.index) - Number(b.meaning.index)
  );
  const sortedPrefixes = prefixWords.sort(
    (a, b) => Number(a.meaning.index) - Number(b.meaning.index)
  );
  ///////////
  const words = [
    ...sortedNouns,
    ...sortedVerbs,
    ...sortedPhrasalVerbs,
    ...sortedAdjectives,
    ...sortedAdverbs,
    ...sortedSuffixes,
    ...sortedInterjections,
    ...sortedPrepositions,
    ...sortedPrefixes,
  ];
  if (data.length !== words.length)
    console.error(
      `THERE IS A PROBLEM. ${data.length - words.length} WORDS WERE MISSED.`
    );
  console.log("words sorted", words);

  ///// EXTRACT THE WORDS:
  // const previousWords = [
  //   "gotta",
  //   "hump",
  //   "hairpiece",
  //   "chalk",
  //   "go through",
  //   "date",
  //   "cafeteria",
  //   "turn out",
  //   "weird",
  //   "grab",
  //   "intestine",
  //   "stuff",
  //   "cleanse",
  //   "aura",
  //   "fixated",
  //   "decaf",
  //   "bridesmaid",
  //   "gravy",
  //   "gravy boat",
  //   "survivor",
  //   "turn on",
  //   "freak out",
  //   "hit",
  //   "strip club",
  //   "strip joint",
  //   "wonder",
  //   "drift apart",
  //   "organ",
  //   "metaphor",
  //   "establish",
  //   "whisker",
  //   "kitten",
  //   "sleigh",
  //   "mitten",
  //   "be for the best",
  //   "wine",
  //   "hit on somebody/something",
  //   "diary",
  //   "catch",
  //   "eyelash",
  //   "suppose",
  //   "head",
  //   "lizard",
  //   "hang out",
  //   "bracket",
  //   "whatsoever",
  //   "bookcase",
  //   "catch on",
  //   "mess",
  //   "mess around with somebody/something",
  //   "mess up",
  //   "mess with somebody/something",
  //   "whipped cream",
  //   "whip",
  //   "horny",
  //   "revelation",
  //   "be more of something than something",
  //   "spit",
  //   "smash",
  //   "get together",
  //   "be on a roll",
  //   "abuse",
  //   "credit",
  //   "snap",
  //   "turtle",
  //   "sophisticated",
  //   "beacon",
  //   "upbeat",
  //   "live off somebody/something",
  //   "give me/it a break!",
  //   "end up",
  //   "albino",
  //   "windshield",
  //   "port",
  //   "aromatherapy",
  //   "something sucks",
  //   "crash",
  //   "split",
  //   "major",
  //   "crush",
  //   "figure",
  //   "geek",
  //   "vulnerable",
  //   "ask",
  //   "act",
  //   "stand up",
  //   "stand-up",
  //   "sit through something",
  //   "club",
  //   "glacier",
  //   "catch up with somebody",
  //   "erect",
  //   "paranoid",
  //   "fluff",
  //   "ammunition",
  //   "chaotic",
  //   "twirl",
  //   "concern",
  //   "engagement",
  //   "dread",
  //   "stomp",
  //   "perspective",
  //   "fit into something",
  //   "be up to somebody",
  //   "presumably",
  //   "sonogram",
  //   "ruin",
  //   "curry",
  //   "have a thing about somebody/something",
  //   "selfish",
  //   "bring something ↔ up",
  //   "heat",
  //   "altar",
  //   "chubby",
  //   "anecdote",
  //   "folk",
  //   "deal",
  //   "deal with somebody/something",
  //   "pro",
  //   "take your time",
  //   "twin",
  //   "identical twin",
  //   "high-powered",
  //   "driven",
  //   "career woman",
  //   "dump",
  //   "steer",
  //   "shell",
  //   "complicated",
  //   "get",
  //   "stuck",
  //   "shake",
  //   "cervix",
  //   "gag",
  //   "instance",
  //   "roll",
  //   "punch",
  //   "table",
  //   "tan",
  //   "maid of honor",
  //   "stick",
  //   "border",
  //   "border on something",
  //   "wind up",
  //   "get/have your (own) way",
  //   "nausea",
  //   "be about to do something",
  //   "tilt",
  //   "well",
  //   "work out",
  //   "hairline",
  //   "Bugs Bunny",
  //   "bunny",
  //   "call (somebody’s) attention to",
  //   "change",
  //   "chase",
  //   "chew",
  //   "come off",
  //   "complain",
  //   "constant",
  //   "convenience",
  //   "coyote",
  //   "crack",
  //   "crooked",
  //   "cut out",
  //   "deal with somebody",
  //   "debt",
  //   "deja vu",
  //   "emphysema",
  //   "endearing",
  //   "even",
  //   "every now and then",
  //   "flaw",
  //   "float",
  //   "foil",
  //   "get over",
  //   "get to do something",
  //   "go off",
  //   "gross",
  //   "herd",
  //   "hitchhike",
  //   "impression",
  //   "index finger",
  //   "innate",
  //   "jeweller",
  //   "karma",
  //   "knuckle",
  //   "leather",
  //   "let one's guard down",
  //   "loosely",
  //   "minion",
  //   "naked",
  //   "nursery rhyme",
  //   "other wise",
  //   "pick somebody",
  //   "pretzel",
  //   "pronounce",
  //   "puff",
  //   "put out",
  //   "put somebody",
  //   "put",
  //   "quit",
  //   "relieve",
  //   "ridiculous",
  //   "rough",
  //   "row",
  //   "saltine",
  //   "skip",
  //   "snort",
  //   "soda",
  //   "softball",
  //   "soften",
  //   "stand",
  //   "statement",
  //   "the bottom line",
  //   "the odds",
  //   "thumb",
  //   "tin",
  //   "tinfoil",
  //   "tip",
  //   "vowel",
  //   "warden",
  //   "worth",
  //   "wrist",
  //   "yardstick",
  //   "adore",
  //   "alphabet soup",
  //   "bash",
  //   "be all over somebody",
  //   "big deal",
  //   "break up",
  // ];

  // data = data.map((item) => item.trim());
  // data = [...new Set(data)];
  // data = data.filter((item) => !previousWords.includes(item));
  // console.log("dddddddd", data);
  ///////////
  return <div></div>;
}

export default App;
